### ISSUE TITLE
:EnDeclaration results in  NvimError('Column value outside range',)

### ISSUE THREAD

**Issue by Ferenc-** [ensime/ensime-vim#123]
Using `:EnDeclaration` in a simple HelloWorld application results in the following backtrace:

```
"src/main/scala/HelloWorld.scala" 7L, 88C
Error detected while processing CursorHold Auto commands for "*.scala":
NvimError('Column value outside range',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/lib/python2.7/site-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/lib/python2.7/site-packages/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/home/ferenc/.config/nvim/plugged/ensime-vim/rplugin/python/ensime.py", line 611, in au_cursor_hold
    self.with_current_client(lambda c: c.on_cursor_hold(filename))
  File "/home/ferenc/.config/nvim/plugged/ensime-vim/rplugin/python/ensime.py", line 515, in with_current_client
    return proc(c)
NvimError: Column value outside range
```

```
> cat .ensime_cache/server.log
14:04:26.346 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
14:04:26.353 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
14:04:26.355 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
14:04:26.392 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
14:04:26.431 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:40508
14:04:26.433 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Bound server on port 40508
14:04:26.433 INFO  None o.e.s.PortUtil$ - creating portfile /mnt/backup/Devel/Scala/my_project/.ensime_cache/port
14:04:27.029 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
  OS : Linux
  Java : Java HotSpot(TM) 64-Bit Server VM 25.66-b17, Java(TM) SE Runtime Environment 1.8.0_66-b17
  Scala : version 2.11.6
  Ensime : 0.9.10-SNAPSHOT
14:04:27.030 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Successfully bound to /127.0.0.1:42514
14:04:27.034 INFO  None o.e.s.PortUtil$ - creating portfile /mnt/backup/Devel/Scala/my_project/.ensime_cache/http
14:04:27.034 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1
14:04:27.320 INFO  None o.e.i.DatabaseService - creating the search database...
14:04:27.484 WARN  None c.j.b.BoneCPConfig - JDBC username was not set in config!
14:04:27.878 INFO  None o.e.i.DatabaseService - ... created the search database
14:04:27.889 INFO  None o.e.i.ClassfileWatcher - Setting up new file watchers
14:04:53.242 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - New connection accepted
14:04:53.284 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/2 a.a.LocalActorRef - unhandled message from Actor[akka://ENSIME/system/IO-TCP-STREAM/server-1-%2F127.0.0.1%3A0/$a#196185933]: ResumeReading
14:04:53.437 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - New connection accepted
14:04:53.986 DEBUG akka://ENSIME/user/$a/0 o.e.s.RequestHandler - ConnectionInfoReq
14:04:53.987 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message ConnectionInfoReq in state awaitingConnectionInfoReq
14:04:53.990 DEBUG akka://ENSIME/user/$a/0 o.e.s.RequestHandler - received handled message ConnectionInfo(None,EnsimeImplementation(ENSIME),0.8.17) in state receive
14:04:54.203 INFO  None o.e.i.SearchService - findStaleFileChecks
14:04:54.204 INFO  None o.e.i.SearchService - removing 0 stale files from the index
14:04:54.206 INFO  None o.e.i.SearchService - findBases
14:04:54.209 INFO  None o.e.i.SearchService - indexBases
14:04:54.234 DEBUG None o.e.i.SearchService - indexing file:///home/ferenc/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar
14:04:54.234 DEBUG None o.e.i.SearchService - indexing file:///usr/java/latest/jre/lib/rt.jar
14:04:55.775 DEBUG akka://ENSIME/user/$a o.e.s.ConnectionHandler - received handled message SendBackgroundMessageEvent(Initializing Analyzer. Please wait...,105)
14:04:55.790 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent in state startup
14:04:55.803 DEBUG akka://ENSIME/user/$a o.e.s.ConnectionHandler - received handled message AnalyzerReadyEvent
14:04:55.804 DEBUG akka://ENSIME/user/$a o.e.s.ConnectionHandler - received handled message FullTypeCheckCompleteEvent
14:04:58.531 DEBUG akka://ENSIME/user/ensime-main/$a/flow-5-2-publisherSource-prefixAndTail a.s.i.PrefixAndTailImpl - Cancelling akka.stream.impl.MultiStreamOutputProcessor$SubstreamOutput@23df7017 (after: 5000 ms)
14:05:09.372 DEBUG None o.e.i.SearchService - committing index to disk...
14:05:10.948 DEBUG None o.e.i.SearchService - ...done committing index
14:05:10.950 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - created 85498 and removed 0 searchable rows
14:05:10.950 DEBUG akka://ENSIME/user/$a o.e.s.ConnectionHandler - received handled message IndexerReadyEvent
14:07:40.330 DEBUG akka://ENSIME/user/$a/1 o.e.s.RequestHandler - SymbolAtPointReq(Left(/mnt/backup/Devel/Scala/my_project/src/main/scala/HelloWorld.scala),83)
14:07:40.332 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message SymbolAtPointReq(Left(/mnt/backup/Devel/Scala/my_project/src/main/scala/HelloWorld.scala),83) in state handleRequests
14:07:40.332 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message SymbolAtPointReq(Left(/mnt/backup/Devel/Scala/my_project/src/main/scala/HelloWorld.scala),83) in state ready
14:07:40.566 DEBUG None o.e.c.RichPresentationCompiler - using symbol of class scala.reflect.internal.Trees$Select tree
14:07:40.573 DEBUG None o.e.c.RichPresentationCompiler - search class Unit: Try Companion
14:07:40.574 DEBUG akka://ENSIME/user/$a/1 o.e.s.RequestHandler - received handled message Some(SymbolInfo(f,f,Some(OffsetSourcePosition(/mnt/backup/Devel/Scala/my_project/src/main/scala/HelloWorld.scala,33)),ArrowTypeInfo(()Unit,1,BasicTypeInfo(Unit,2,Class,scala.Unit,List(),List(),None,None),List(ParamSectionInfo
14:09:15.161 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/3 a.a.LocalActorRef - unhandled message from Actor[akka://ENSIME/system/IO-TCP-STREAM/server-1-%2F127.0.0.1%3A0/$b#-1393277026]: ResumeReading
```

```
> cat .ensime_cache/server.log
2015-12-03 14:04:53.732539: send_request: in
2015-12-03 14:04:53.778263: send: in
2015-12-03 14:04:53.833292: send: {"callId": 0, "req": {"typehint": "ConnectionInfoReq"}}
2015-12-03 14:04:54.937868: unqueue: result received {
  "callId": 0,
  "payload": {
    "typehint": "ConnectionInfo",
    "implementation": {
      "name": "ENSIME"
    },
    "version": "0.8.17"
  }
}
2015-12-03 14:04:55.027270: handle_payload: in {u'implementation': {u'name': u'ENSIME'}, u'typehint': u'ConnectionInfo', u'version': u'0.8.17'}
2015-12-03 14:04:55.989603: unqueue: result received {
  "payload": {
    "typehint": "SendBackgroundMessageEvent",
    "detail": "Initializing Analyzer. Please wait...",
    "code": 105
  }
}
2015-12-03 14:04:56.089297: handle_payload: in {u'code': 105, u'typehint': u'SendBackgroundMessageEvent', u'detail': u'Initializing Analyzer. Please wait...'}
2015-12-03 14:04:56.965597: unqueue: result received {
  "payload": {
    "typehint": "AnalyzerReadyEvent"
  }
}
2015-12-03 14:04:57.052661: handle_payload: in {u'typehint': u'AnalyzerReadyEvent'}
2015-12-03 14:04:57.096931: message: in
2015-12-03 14:04:57.151442: ensime analyzer ready
2015-12-03 14:04:58.479249: unqueue: result received {
  "payload": {
    "typehint": "FullTypeCheckCompleteEvent"
  }
}
2015-12-03 14:04:58.557327: handle_payload: in {u'typehint': u'FullTypeCheckCompleteEvent'}
2015-12-03 14:05:11.639855: unqueue: result received {
  "payload": {
    "typehint": "IndexerReadyEvent"
  }
}
2015-12-03 14:05:11.799525: handle_payload: in {u'typehint': u'IndexerReadyEvent'}
2015-12-03 14:05:11.887187: message: in
2015-12-03 14:05:11.931453: ensime indexer ready
2015-12-03 14:05:36.823194: en_classpath: in
2015-12-03 14:07:39.714447: open_declaration: in
2015-12-03 14:07:39.879602: path: in
2015-12-03 14:07:39.947780: path: in
2015-12-03 14:07:40.013113: send_request: in
2015-12-03 14:07:40.101293: send: in
2015-12-03 14:07:40.189803: send: {"callId": 1, "req": {"typehint": "SymbolAtPointReq", "file": "/mnt/backup/Devel/Scala/my_project/src/main/scala/HelloWorld.scala", "point": 83}}
2015-12-03 14:07:41.258614: unqueue: result received {
  "callId": 1,
  "payload": {
    "name": "f",
    "localName": "f",
    "typehint": "SymbolInfo",
    "declPos": {
      "typehint": "OffsetSourcePosition",
      "file": "/mnt/backup/Devel/Scala/my_project/src/main/scala/HelloWorld.scala",
      "offset": 33
    },
    "type": {
      "resultType": {
        "name": "Unit",
        "fullName": "scala.Unit",
        "typehint": "BasicTypeInfo",
        "typeId": 2,
        "typeArgs": [],
        "members": [],
        "declAs": {
          "typehint": "Class"
        }
      },
      "name": "()Unit",
      "paramSections": [{
        "params": [],
        "isImplicit": false
      }],
      "typehint": "ArrowTypeInfo",
      "typeId": 1
    },
    "isCallable": true,
    "ownerTypeId": 3
  }
}
2015-12-03 14:07:41.329318: handle_payload: in {u'typehint': u'SymbolInfo', u'name': u'f', u'localName': u'f', u'isCallable': True, u'type': {u'resultType': {u'typeId': 2, u'typehint': u'BasicTypeInfo', u'name': u'Unit', u'typeArgs': [], u'declAs': {u'typehint': u'Class'}, u'members': [], u'fullName': u'scala.Unit'}, u'typehint': u'ArrowTypeInfo', u'name': u'()Unit', u'paramSections': [{u'params': [], u'isImplicit': False}], u'typeId': 1}, u'ownerTypeId': 3, u'declPos': {u'typehint': u'OffsetSourcePosition', u'file': u'/mnt/backup/Devel/Scala/my_project/src/main/scala/HelloWorld.scala', u'offset': 33}}
2015-12-03 14:07:41.395604: message: in
2015-12-03 14:07:41.451098: /mnt/backup/Devel/Scala/my_project/src/main/scala/HelloWorld.scala
2015-12-03 14:07:41.509561: path: in
2015-12-03 14:07:41.562853: set_cursor: (1, -19)
2015-12-03 14:08:53.724616: buffer_leave: src/main/scala/HelloWorld.scala
2015-12-03 14:09:15.016854: teardown: in

```

**Comment by vito-c** [comment]
I am also getting this error.

**Comment by vito-c** [comment]
Fixed here: https://github.com/ensime/ensime-vim/pull/124

**Comment by yazgoo** [comment]
Closing this after #124 merge, please re-open if #124 did not fix it.
