### ISSUE TITLE
Blocking BufEnter command

### ISSUE THREAD

**Issue by vito-c** [ensime/ensime-vim#138]
````
Error detected while processing BufEnter Auto commands for "*.scala":
WebSocketConnectionClosedException('Connection is already closed.',)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/Library/Python/2.7/site-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/Library/Python/2.7/site-packages/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/Users/vito-c/.vim/bundle/ensime-vim/rplugin/python/ensime.py", line 609, in au_buf_enter
    self.with_current_client(lambda c: c.buffer_enter(filename), True, True)
  File "/Users/vito-c/.vim/bundle/ensime-vim/rplugin/python/ensime.py", line 523, in with_current_client
    c = self.current_client(create, quiet, allow_classpath_file_creation)
WebSocketConnectionClosedException: Connection is already closed.
Press ENTER or type command to continue
````

I get this error sometime when trying to open multiple instances of nvim in the same project directory. It also seems to be a blocking call and takes awhile to timeout.

**Comment by jvican** [comment]
Fixed by last PR https://github.com/ensime/ensime-vim/pull/156. If it happens again, I'll reopen the ticket.
