### ISSUE TITLE
Neovim import error when vim is executed and neovim module is not installed

### ISSUE THREAD

**Issue by jvican** [ensime/ensime-vim#152]
```Traceback (most recent call last):                                                                                                                            
  File "<string>", line 1, in <module>                                                                                                                        
  File "/Users/v751429/code/vim-config/bundle/ensime-vim/autoload/ensime.vim.py", line 19, in <module>                                                        
    from ensime_shared.ensime import Ensime                                                                                                                   
  File "/Users/v751429/code/vim-config/bundle/ensime-vim/ensime_shared/ensime.py", line 14, in <module>                                                       
    import neovim                                                                                                                                             
ImportError: No module named neovim                                                                                                                           
Error detected while processing function ensime#au_buf_enter..<SNR>66_call_plugin:                                                                            
line   14:                                                                                                                                                    
E605: Exception not caught: <type 'exceptions.NameError'>:name 'ensime_plugin' is not defined```

**Comment by alexDeCastroAtGit** [comment]
I'm getting the same error...

```

> Error detected while processing function ensime#com_en_add_import[1]..<SNR>28_ca
> ll_plugin:
> line   15:
> E605: Exception not caught: <type 'exceptions.NameError'>:name 'ensime_plugin' i
> s not defined

Do you remember what was done to recover from this error? I'm following the instructions on 
[(http://ensime.github.io/editors/vim/install/)]
but to no success...

```

**Comment by ktonga** [comment]
Hey @alexDeCastroAtGit `ensime-vim` is a neovim remote plugin, so you need to run `:UpdateRemotePlugins`. Maybe that's your problem
