### ISSUE TITLE
Cannot make bridge file on OS X

### ISSUE THREAD

**Issue by geowa4** [ensime/ensime-vim#17]
When running ensime-vim with either vim or neovim, I get the following error.

```
/usr/local/lib/ruby/gems/2.2.0/gems/ensime_bridge-0.0.4/lib/ensime_bridge.rb:11:in `read': No such file or directory @ rb_sysopen - .ensime_cache/bridge (Errno::ENOENT)
        from /usr/local/lib/ruby/gems/2.2.0/gems/ensime_bridge-0.0.4/lib/ensime_bridge.rb:11:in `get_socket'
        from /usr/local/lib/ruby/gems/2.2.0/gems/ensime_bridge-0.0.4/lib/ensime_bridge.rb:32:in `remote_stop'
        from /usr/local/lib/ruby/gems/2.2.0/gems/ensime_bridge-0.0.4/bin/ensime_bridge:11:in `<top (required)>'
        from /usr/local/bin/ensime_bridge:23:in `load'
        from /usr/local/bin/ensime_bridge:23:in `<main>'
```

Looking through the code, I'm not sure why it would do that. Let me know if you'd like me to do anything to help identify and fix the issue.

**Comment by siegelzero** [comment]
I get something similar when starting in Ubuntu 12.04.
```
/var/lib/gems/1.9.1/gems/ensime_bridge-0.0.4/lib/ensime.rb:19:in `read': No such file or directory - .ensime (Errno::ENOENT)
    from /var/lib/gems/1.9.1/gems/ensime_bridge-0.0.4/lib/ensime.rb:19:in `initialize'
    from /var/lib/gems/1.9.1/gems/ensime_bridge-0.0.4/lib/ensime_bridge.rb:24:in `new'
    from /var/lib/gems/1.9.1/gems/ensime_bridge-0.0.4/lib/ensime_bridge.rb:24:in `initialize'
    from /var/lib/gems/1.9.1/gems/ensime_bridge-0.0.4/bin/ensime_bridge:8:in `new'
    from /var/lib/gems/1.9.1/gems/ensime_bridge-0.0.4/bin/ensime_bridge:8:in `<top (required)>'
    from /usr/local/bin/ensime_bridge:19:in `load'
    from /usr/local/bin/ensime_bridge:19:in `<main>'
```

**Comment by siegelzero** [comment]
The error `No such file or directory - .ensime` seems to indicate an issue with the ensime configuration. However, I've been using the spacemacs ensime plugin successfully with the same project for quite a while, so I don't suspect that is the issue.

**Comment by yazgoo** [comment]
This exception happens when there is no .ensime file in the directory where you start vim.
Was it the case for you ?
This is a bad behaviour for a plugin, I guess it should not initialize itself in that case.

**Comment by siegelzero** [comment]
@yazgoo I'm starting `ensime_bridge` from the directory with the `.ensime` file. I see no errors on that side. I'm also starting vim from the directory with the `.ensime` file. I've tried starting vim with `vim <path-to-file>` as well as starting vim, and then `:e`-ing the file. I get the same error in both cases as soon as the scala file is opened.

**Comment by yazgoo** [comment]
Thanks @siegelzero .
Could you please add: 

throw Dir.pwd

to ensime.rb before line 19 ?
This will tell us the working dir from which the .ensime file is being read.

**Comment by siegelzero** [comment]
Perhaps as expected, this causes `ensime_bridge` to halt with an uncaught throw error. However, it does display the absolute path to the directory containing the `.ensime` file.

**Comment by yazgoo** [comment]
Even when running vim ?

**Comment by siegelzero** [comment]
OK, I misunderstood. Starting vim shows the path to the dir containing the source file I'm trying to open (not the dir containing `.ensime`).

**Comment by yazgoo** [comment]
Do you have autochdir enabled, which can be checked by running:

    :set

under vim ?

**Comment by siegelzero** [comment]
Yes, autochdir is enabled. Disabling autochdir and starting vim with the `throw` line now shows the correct directory. Undoing the `throw` line and starting vim now gives a new error:
```
/var/lib/gems/1.9.1/gems/ensime_bridge-0.0.4/lib/ensime_bridge.rb:11:in `read': No such file or directory - .ensime_cache/bridge (Errno::ENOENT)
	from /var/lib/gems/1.9.1/gems/ensime_bridge-0.0.4/lib/ensime_bridge.rb:11:in `get_socket'
	from /var/lib/gems/1.9.1/gems/ensime_bridge-0.0.4/lib/ensime_bridge.rb:32:in `remote_stop'
	from /var/lib/gems/1.9.1/gems/ensime_bridge-0.0.4/bin/ensime_bridge:11:in `<top (required)>'
	from /usr/local/bin/ensime_bridge:19:in `load'
	from /usr/local/bin/ensime_bridge:19:in `<main>'
```
After deleting `.ensime_cache` and restarting vim I still see the error.

**Comment by geowa4** [comment]
@siegelzero, it seems like you have a different issue than I do. Yours is an error finding .ensime, while mine is not able to create the bridge.

**Comment by geowa4** [comment]
While I don't have `.ensime_cache/bridge`, I have a file called `.ensime_cache/port`, which has the port a Java process is listening on.

**Comment by yazgoo** [comment]
@geowa4 @siegelzero looks like you both have the same stack trace now.
This is displayed when leaving vim.
Don't you have another error displayed in vim before leaving ?

**Comment by siegelzero** [comment]
```
Error detected while processing function Enunqueue:
Traceback (most recent call last):
Error detected while processing function Enunqueue:
  File "<string>", line 1, in <module>
Error detected while processing function Enunqueue:
  File "<string>", line 116, in unqueue
Error detected while processing function Enunqueue:
  File "<string>", line 32, in get_socket
Error detected while processing function Enunqueue:
  File "<string>", line 25, in get_cache_port
Error detected while processing function Enunqueue:
IOError: [Errno 2] No such file or directory: '.ensime_cache/bridge'
Error detected while processing function Enunqueue:
E121: Undefined variable: g:__result
Error detected while processing function Enunqueue:
E15: Invalid expression: g:__result
Error detected while processing function Enunqueue:
E108: No such variable: "g:__result"
Error detected while processing function Enunqueue:
E121: Undefined variable: res
Error detected while processing function Enunqueue:
E15: Invalid expression: res
```
I'm seeing this (and some noise) in `:messages`. It seems that it's complaining about `scala_ensime.vim`

**Comment by geowa4** [comment]
After updating, I do get the above message. I also get the following. It seems like it's also not cleaning up after itself in this failure scenario.

```
Exception in thread "main" java.io.IOException: An ENSIME server might be open already for this project. If you are sure this is not the case, please delete /path/to/.ensime_cache/port and try again
        at org.ensime.server.Server.writePort(Server.scala:118)
        at org.ensime.server.Server.<init>(Server.scala:68)
        at org.ensime.server.Server$.initialiseServer(Server.scala:42)
        at org.ensime.server.Server$.main(Server.scala:38)
        at org.ensime.server.Server.main(Server.scala)
```

**Comment by geowa4** [comment]
Oh, I should also mention that a file called `bridge.log` showed up in `.ensime_cache` after updating.

**Comment by yazgoo** [comment]
@geowa4: about the message you about the port file, there are two possibilities:
- ensime server is already running, which you should see with a `ps -ef | grep java`
- ensime server ended without removing port and http file, in which case you should delete these first

**Comment by yazgoo** [comment]
@geowa4 @siegelzero about this other error, did you try to update your plugins since yesterday ?
There was the following commit that should catch this exception:

https://github.com/yazgoo/ensime-vim/commit/d2f4b0404cd48429d30f8a69a5aace44ad31ecc0#diff-99bec7b4ad95b9efced2f99f97abe6b1

**Comment by geowa4** [comment]
I just updated everything. I'm now getting this while I have a Scala file open:

```
$ ls .ensime_cache
bridge.log     ensime-vim.log index-1.0      port           sql-1.0
```

There's no `.ensime_cache/http`.  These are the contents of `ensime-vim.log`:

```
2015-09-03 10:57:00: __init__: in
2015-09-03 10:57:00: unqueue: in
2015-09-03 10:57:00: setup: in
2015-09-03 10:57:00: ensime_bridge: lanching ensime_bridge --quiet
2015-09-03 10:57:00: get_socket: in
2015-09-03 10:57:00: get_cache_port: in
2015-09-03 10:57:01: unqueue: in
2015-09-03 10:57:01: setup: in
2015-09-03 10:57:01: get_socket: in
2015-09-03 10:57:01: get_cache_port: in
2015-09-03 10:57:01: unqueue: in
2015-09-03 10:57:01: setup: in
2015-09-03 10:57:01: get_socket: in
2015-09-03 10:57:01: get_cache_port: in
2015-09-03 10:57:02: unqueue: in
2015-09-03 10:57:02: setup: in
2015-09-03 10:57:02: get_socket: in
2015-09-03 10:57:02: get_cache_port: in
2015-09-03 10:57:02: unqueue: in
2015-09-03 10:57:02: setup: in
2015-09-03 10:57:02: get_socket: in
2015-09-03 10:57:02: get_cache_port: in
2015-09-03 10:57:04: unqueue: in
2015-09-03 10:57:04: setup: in
2015-09-03 10:57:04: get_socket: in
2015-09-03 10:57:04: get_cache_port: in
2015-09-03 10:57:04: unqueue: in
2015-09-03 10:57:04: setup: in
2015-09-03 10:57:04: get_socket: in
2015-09-03 10:57:04: get_cache_port: in
2015-09-03 10:57:05: unqueue: in
2015-09-03 10:57:05: setup: in
2015-09-03 10:57:05: get_socket: in
2015-09-03 10:57:05: get_cache_port: in
2015-09-03 10:57:05: unqueue: in
2015-09-03 10:57:05: setup: in
2015-09-03 10:57:05: get_socket: in
2015-09-03 10:57:05: get_cache_port: in
2015-09-03 10:57:05: unqueue: in
2015-09-03 10:57:05: setup: in
2015-09-03 10:57:05: get_socket: in
2015-09-03 10:57:05: get_cache_port: in
2015-09-03 10:57:05: unqueue: in
2015-09-03 10:57:05: setup: in
2015-09-03 10:57:05: get_socket: in
2015-09-03 10:57:05: get_cache_port: in
2015-09-03 10:57:06: unqueue: in
2015-09-03 10:57:06: setup: in
2015-09-03 10:57:06: get_socket: in
2015-09-03 10:57:06: get_cache_port: in
2015-09-03 10:57:08: unqueue: in
2015-09-03 10:57:08: setup: in
2015-09-03 10:57:08: get_socket: in
2015-09-03 10:57:08: get_cache_port: in
2015-09-03 10:57:09: unqueue: in
2015-09-03 10:57:09: setup: in
2015-09-03 10:57:09: get_socket: in
2015-09-03 10:57:09: get_cache_port: in
2015-09-03 10:57:11: unqueue: in
2015-09-03 10:57:11: setup: in
2015-09-03 10:57:11: get_socket: in
2015-09-03 10:57:11: get_cache_port: in
2015-09-03 10:57:18: doc_uri: in
2015-09-03 10:57:18: path_start_size: in
2015-09-03 10:57:18: cursor: in
2015-09-03 10:57:18: cursor: in
2015-09-03 10:57:18: path: in
2015-09-03 10:57:18: cursor: in
2015-09-03 10:57:18: path: in
2015-09-03 10:57:18: send_request: in
2015-09-03 10:57:18: send: in
2015-09-03 10:57:18: get_socket: in
2015-09-03 10:57:18: get_cache_port: in
2015-09-03 10:57:18: send: could not get socket
2015-09-03 10:57:19: unqueue: in
2015-09-03 10:57:19: setup: in
2015-09-03 10:57:19: get_socket: in
2015-09-03 10:57:19: get_cache_port: in
2015-09-03 10:57:19: unqueue: in
2015-09-03 10:57:19: setup: in
2015-09-03 10:57:19: get_socket: in
2015-09-03 10:57:19: get_cache_port: in
2015-09-03 10:57:24: teardown: in
2015-09-03 10:57:24: ensime_bridge: lanching ensime_bridge stop
2015-09-03 10:58:37: __init__: in
2015-09-03 10:58:37: unqueue: in
2015-09-03 10:58:37: setup: in
2015-09-03 10:58:37: ensime_bridge: lanching ensime_bridge --quiet
2015-09-03 10:58:37: get_socket: in
2015-09-03 10:58:37: get_cache_port: in
2015-09-03 10:58:38: unqueue: in
2015-09-03 10:58:38: setup: in
2015-09-03 10:58:38: get_socket: in
2015-09-03 10:58:38: get_cache_port: in
2015-09-03 10:58:38: unqueue: in
2015-09-03 10:58:38: setup: in
2015-09-03 10:58:38: get_socket: in
2015-09-03 10:58:38: get_cache_port: in
2015-09-03 10:58:40: unqueue: in
2015-09-03 10:58:40: setup: in
2015-09-03 10:58:40: get_socket: in
2015-09-03 10:58:40: get_cache_port: in
2015-09-03 10:58:42: unqueue: in
2015-09-03 10:58:42: setup: in
2015-09-03 10:58:42: get_socket: in
2015-09-03 10:58:42: get_cache_port: in
2015-09-03 10:58:46: unqueue: in
2015-09-03 10:58:46: setup: in
2015-09-03 10:58:46: get_socket: in
2015-09-03 10:58:46: get_cache_port: in
2015-09-03 10:58:46: unqueue: in
2015-09-03 10:58:46: setup: in
2015-09-03 10:58:46: get_socket: in
2015-09-03 10:58:46: get_cache_port: in
2015-09-03 10:58:47: unqueue: in
2015-09-03 10:58:47: setup: in
2015-09-03 10:58:47: get_socket: in
2015-09-03 10:58:47: get_cache_port: in
2015-09-03 10:58:51: doc_uri: in
2015-09-03 10:58:51: path_start_size: in
2015-09-03 10:58:51: cursor: in
2015-09-03 10:58:51: cursor: in
2015-09-03 10:58:51: path: in
2015-09-03 10:58:51: cursor: in
2015-09-03 10:58:51: path: in
2015-09-03 10:58:51: send_request: in
2015-09-03 10:58:51: send: in
2015-09-03 10:58:51: get_socket: in
2015-09-03 10:58:51: get_cache_port: in
2015-09-03 10:58:51: send: could not get socket
2015-09-03 10:58:53: unqueue: in
2015-09-03 10:58:53: setup: in
2015-09-03 10:58:53: get_socket: in
2015-09-03 10:58:53: get_cache_port: in
2015-09-03 10:58:54: unqueue: in
2015-09-03 10:58:54: setup: in
2015-09-03 10:58:54: get_socket: in
2015-09-03 10:58:54: get_cache_port: in
2015-09-03 10:59:01: type: in
2015-09-03 10:59:01: path_start_size: in
2015-09-03 10:59:01: cursor: in
2015-09-03 10:59:01: cursor: in
2015-09-03 10:59:01: path: in
2015-09-03 10:59:01: cursor: in
2015-09-03 10:59:01: path: in
2015-09-03 10:59:01: send_request: in
2015-09-03 10:59:01: send: in
2015-09-03 10:59:01: get_socket: in
2015-09-03 10:59:01: get_cache_port: in
2015-09-03 10:59:01: send: could not get socket
```

**Comment by geowa4** [comment]
After removing `.ensime_cache` and restarting either Vim or Neovim, that directory will not recreate. 

```
$ /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/logger.rb:636:in `initialize': No such file or directory @ rb_sysopen - .ensime_cache/bridge.log (Errno::ENOENT)
        from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/logger.rb:636:in `open'
        from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/logger.rb:636:in `create_logfile'
        from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/logger.rb:630:in `rescue in open_logfile'
        from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/logger.rb:627:in `open_logfile'
        from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/logger.rb:584:in `initialize'
        from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/logger.rb:318:in `new'
        from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/logger.rb:318:in `initialize'
        from /usr/local/lib/ruby/gems/2.2.0/gems/ensime_bridge-0.0.5/lib/ensime_bridge.rb:31:in `new'
        from /usr/local/lib/ruby/gems/2.2.0/gems/ensime_bridge-0.0.5/lib/ensime_bridge.rb:31:in `initialize'
        from /usr/local/lib/ruby/gems/2.2.0/gems/ensime_bridge-0.0.5/bin/ensime_bridge:8:in `new'
        from /usr/local/lib/ruby/gems/2.2.0/gems/ensime_bridge-0.0.5/bin/ensime_bridge:8:in `<top (required)>'
        from /usr/local/bin/ensime_bridge:23:in `load'
        from /usr/local/bin/ensime_bridge:23:in `<main>'
```

**Comment by yazgoo** [comment]
The java process probably was not stopped because the bridge crashed.
Could you update the gem to 0.0.8 ? This version now creates the .ensime_cache directory if required.
Also, could you send your bridge.log ?
If you want, we can continue on gitter: https://gitter.im/ensime/ensime-vim

Thanks

**Comment by geowa4** [comment]
Thanks to @yazgoo, this gets a lot further for me than it did when I opened this issue. Based on that effort and discussions on Gitter, I think it's best to close this issue.
