### ISSUE TITLE
Test coverage fails to run on CI

### ISSUE THREAD

**Issue by ChrisCoffey** [ensime/ensime-vim#173]
```
Successfully installed python-coveralls PyYAML coverage sh
Cleaning up...
$ coverage run --include=ensime_launcher/__init__.py,rplugin/python/ensime.py spec/ensime.py
EE.....
======================================================================
ERROR: test_ensime (__main__.TestEnsime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spec/ensime.py", line 257, in test_ensime
    assert(self.ensime.with_current_client(lambda c: None) == None)
  File "spec/../rplugin/python/ensime.py", line 525, in with_current_client
    c = self.current_client(create, quiet, allow_classpath_file_creation)
TypeError: fake_current_client() takes no arguments (3 given)

======================================================================
ERROR: test_ensime_client (__main__.TestEnsime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spec/ensime.py", line 167, in test_ensime_client
    for typehint in ["NewScalaNotesEvent", "SymbolInfo", "IndexerReadyEvent", "AnalyzerReadyEvent", "BasicTypeInfo", "StringResponse", "CompletionInfoList"]]
  File "spec/../rplugin/python/ensime.py", line 350, in handle_payload
    self.show_type(payload)
  File "spec/../rplugin/python/ensime.py", line 366, in show_type
    if payload["typeArgs"] != []:
KeyError: 'typeArgs'

----------------------------------------------------------------------
Ran 7 tests in 0.227s
```

I'll look into this later today unless someone jumps on it.

**Comment by jvican** [comment]
Hi @ChrisCoffey, don't care about the tests, they've been failing for ages and we have to re-engineer the test suite. See #136.
