### ISSUE TITLE
UpdateRemotePlugins error in neovim

### ISSUE THREAD

**Issue by vito-c** [ensime/ensime-vim#337]
Running `UpdateRemotePlugins` gives the below error in neovim

```
encountered ImportError loading plugin at /Users/vitocutten/.vim/bundle/ensime-vim/rplugin/python/ensime.py: No module named sexpdata
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/neovim/plugin/host.py", line 119, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/Users/vitocutten/.vim/bundle/ensime-vim/rplugin/python/ensime.py", line 21, in <module>
    from ensime_shared.ensime import Ensime  # noqa: E402
  File "/Users/vitocutten/.vim/bundle/ensime-vim/ensime_shared/ensime.py", line 5, in <module>
    from .client import EnsimeClientV1, EnsimeClientV2
  File "/Users/vitocutten/.vim/bundle/ensime-vim/ensime_shared/client.py", line 14, in <module>
    from .config import feedback, gconfig, LOG_FORMAT
  File "/Users/vitocutten/.vim/bundle/ensime-vim/ensime_shared/config.py", line 6, in <module>
    import sexpdata
ImportError: No module named sexpdata
remote/host: python host registered plugins []
remote/host: generated the manifest file in "/Users/vitocutten/GDrive/pirate-vim/.init.vim-rplugin~"
````

**Comment by ches** [comment]
Hi,

It looks like your missing the sexpdata dependency, or it's not installed where the Python version that your Vim is built against can find it. Check out [the troubleshooting page][1] for pointers on this, the first item under "Common Issues" should help.

[1]: https://ensime.github.io/editors/vim/troubleshooting/
