### ISSUE TITLE
Many errors when starting neovim after installing ensime-vim

### ISSUE THREAD

**Issue by xanderdunn** [ensime/ensime-vim#38]
neovim: 
```bash
NVIM 0.0.0-alpha+201509140855 (compiled Sep 14 2015 10:47:40)
Commit: 6bcbb18dc88d9b84f71c09450af10f8f537a8a68
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150914-27101-byxlk7/build/config -I/tmp/neovim20150914-27101-byxlk7/src -I/tmp/neovim20150914-27101-byxlk7/deps-build/usr/include -I/tmp/neovim20150914-27101-byxlk7/deps-build/usr/include -I/tmp/neovim20150914-27101-byxlk7/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20150914-27101-byxlk7/deps-build/usr/include -I/tmp/neovim20150914-27101-byxlk7/deps-build/usr/include -I/tmp/neovim20150914-27101-byxlk7/deps-build/usr/include -I/tmp/neovim20150914-27101-byxlk7/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim20150914-27101-byxlk7/build/src/nvim/auto -I/tmp/neovim20150914-27101-byxlk7/build/include
Compiled by admin@Xanders-MacBook-Pro.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

After I install this plugin, here is the beginning portion of the error messages I get when I start neovim:
```bash
Error detected while processing function Enunqueue..provider#python#Call:
line   18:
KeyError('scala-version',)
Press ENTER or type command to continue
Error detected while processing function Enunqueue..provider#python#Call:
line   18:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function Enunqueue..provider#python#Call:
line   18:
  File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 177, in handler
Press ENTER or type command to continue
Error detected while processing function Enunqueue..provider#python#Call:
line   18:
    rv = self._request_cb(name, args)
Press ENTER or type command to continue
Error detected while processing function Enunqueue..provider#python#Call:
line   18:
  File "/usr/local/lib/python2.7/site-packages/neovim/api/common.py", line 237, in filter_request_cb
Press ENTER or type command to continue
Error detected while processing function Enunqueue..provider#python#Call:
line   18:
    walk(self._in, args, self, name, 'request'))
Press ENTER or type command to continue
Error detected while processing function Enunqueue..provider#python#Call:
line   18:
  File "/usr/local/lib/python2.7/site-packages/neovim/plugin/host.py", line 65, in _on_request
Press ENTER or type command to continue
Error detected while processing function Enunqueue..provider#python#Call:
line   18:
    rv = handler(*args)
Press ENTER or type command to continue
Error detected while processing function Enunqueue..provider#python#Call:
line   18:
  File "/usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/provider/script_host.py", line 76, in python_execute
Press ENTER or type command to continue
Error detected while processing function Enunqueue..provider#python#Call:
line   18:
    exec(script, self.module.__dict__)
Press ENTER or type command to continue
Error detected while processing function Enunqueue..provider#python#Call:
line   18:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function Enunqueue..provider#python#Call:
line   18:
KeyError: 'scala-version'
Press ENTER or type command to continue
Error detected while processing function Enunqueue..provider#python#Call:
```

I installed both `websocket-client` and `ensime_launcher` with pip and pip3.  

I have `export BROWSER=safari` in my ~/.profile.  I'm using Scala 2.11.7.

**Comment by yazgoo** [comment]
Did you install neovim python package ?

    pip install neovim

**Comment by xanderdunn** [comment]
`neovim` is installed both with `pip` and `pip3`.  However, perhaps these errors are due to my setting up the gradle ensime plugin instead of the sbt ensime plugin.  I'll try setting up sbt and see how it goes.

**Comment by xanderdunn** [comment]
Using sbt was the key to resolving these errors.  I didn't realize it was integral to the plugin's operation.  I added the sbt plugin to my plugins.sbt and ran `sbt gen-ensime` and these errors were cleared up.
