### ISSUE TITLE
Encoding issue in autocomplete

### ISSUE THREAD

**Issue by 2chilled** [ensime/ensime-vim#392]
### Steps to reproduce

1. Use newest ensime-vim version
2. Use newest deoplete version
2. Use ensime-server 2.0.0-SNAPSHOT
3. `let ensime_server_v2=1` in vimrc
4. NVIM 0.1.7                                                  
5.  Configure newest version of https://github.com/atnos-org/eff in sbt
6. Try autocompleting `org.atnos.eff.Interpret.`

### Expected behaviour
autocompletions should be shown
### Actual behaviour
error caught in async handler '/home/chief/vimconfig/.vim/bundle/ensime-vim/rplugin/python/ensime.py:function:EnTick ([6],)'                                                                                    
Traceback (most recent call last):                                                                                                                                                                              
  File "/home/chief/vimconfig/.vim/bundle/ensime-vim/rplugin/python/ensime.py", line 184, in tick                                                                                                               
    super(NeovimEnsime, self).fun_en_tick(timer)                                                                                                                                                                
  File "/home/chief/vimconfig/.vim/bundle/ensime-vim/ensime_shared/ensime.py", line 305, in fun_en_tick                                                                                                         
    self.tick_clients()                                                                                                                                                                                         
  File "/home/chief/vimconfig/.vim/bundle/ensime-vim/ensime_shared/ensime.py", line 168, in tick_clients                                                                                                        
    self._ticker.tick(client)                                                                                                                                                                                   
  File "/home/chief/vimconfig/.vim/bundle/ensime-vim/ensime_shared/ticker.py", line 21, in tick                                                                                                                 
    client.tick(filename)                                                                                                                                                                                       
  File "/home/chief/vimconfig/.vim/bundle/ensime-vim/ensime_shared/client.py", line 614, in tick                                                                                                                
    self.unqueue_and_display(filename)                                                                                                                                                                          
  File "/home/chief/vimconfig/.vim/bundle/ensime-vim/ensime_shared/client.py", line 604, in unqueue_and_display                                                                                                 
    self.unqueue()                                                                                                                                                                                              
  File "/home/chief/vimconfig/.vim/bundle/ensime-vim/ensime_shared/client.py", line 593, in unqueue                                                                                                             
    self.handle_incoming_response(call_id, _json["payload"])                                                                                                                                                    
  File "/home/chief/vimconfig/.vim/bundle/ensime-vim/ensime_shared/protocol.py", line 60, in handle_incoming_response                                                                                           
    handler(call_id, payload)                                                                                                                                                                                   
  File "/home/chief/vimconfig/.vim/bundle/ensime-vim/ensime_shared/protocol.py", line 225, in handle_completion_info_list                                                                                       
    self.suggestions = [completion_to_suggest(c) for c in completions]                                                                                                                                          
  File "/home/chief/vimconfig/.vim/bundle/ensime-vim/ensime_shared/symbol_format.py", line 14, in completion_to_suggest                                                                                         
    "abbr": formatted_completion_sig(completion),                                                                                                                                                               
  File "/home/chief/vimconfig/.vim/bundle/ensime-vim/ensime_shared/symbol_format.py", line 38, in formatted_completion_sig                                                                                      
    f_sections = [formatted_param_section(ps) for ps in sections]                                                                                                                                               
  File "/home/chief/vimconfig/.vim/bundle/ensime-vim/ensime_shared/symbol_format.py", line 52, in formatted_param_section                                                                                       
    return "({}{})".format(implicit, concat_params(s_params))                                                                                                                                                   
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03b2' in position 29: ordinal not in range(128)

**Comment by 2chilled** [comment]
```
import sys
reload(sys)
sys.setdefaultencoding('UTF8')
```
on top of `symbol_format.py` fixes this issue, but I'm sure there's a cleaner solution ;)

**Comment by ktonga** [comment]
@ches given your vast experience with Python... WDYT 'bout this "fix"?
