### ISSUE TITLE
Browsing doc via EnDocBrowse results in error & EnDocUri does not work

### ISSUE THREAD

**Issue by yelled1** [ensime/ensime-vim#407]
### Steps to reproduce

1. open editor & I see "[ensime] Analyzer ready" msg
2. from editor type : EnDocUri  to look at definition (somehow sometimes it does not work)
3. so I use :EnDocBrowse instead (error occurs)

### Expected behaviour
I get to see the documentation & go back to merry editing
...

### Actual behaviour
Above is not consistent sometimes EnDocBrowse does not EnDocUri works & other way around some other times.

opened http://127.0.0.1:37296/docs/spark-catalyst_2.11-2.2.0-javadoc.jar/index.html#org.apache.spark.sql.types.StructType$
up. as soon as that happens I get 
```
 Error detected while processing function EnTick: line 1: 
 E475 Invalid argument: Channel doesn't exist" 
```

And annoyingly this msg continues until I quit neovim / nyovim.
Here's screen shot [https://github.com/yelled1/uMarkCLewiss/blob/master/Screenshot%20from%202017-09-30%2017-46-37.png](url)
https://github.com/yelled1/uMarkCLewiss
nyaovim 0.0.22
nvim v0.2.1-dev
Ubuntu 16.04 64 bit
Another thing is if I invoke :EnDocUri after :EnDocBrowse's error appears, then I get
```
E475 Invalid argument: Channel doesn't exist" 
Invalid Channel 2

```
See [https://github.com/yelled1/uMarkCLewiss/blob/master/Screenshot%20from%202017-09-30%2018-01-45.png](url)

**Comment by ches** [comment]
Hi, thanks for the report.

From the `EnTick` this could be something related to our use of Vim timers which is relatively new (#374). I so far cannot reproduce your errors, but let me check that a few simple things don't help before going further:

- Could you make sure you're using the latest Neovim Python client? `pip2 install --upgrade neovim` and confirm in Neovim that `:python print('test')` is working.
- Run `:UpdateRemotePlugins` for good measure and restart Neovim.

I'm really not familiar with NyaoVim so it would be easiest to try to debug in Neovim and see if we can solve that first.

If the above doesn't help, please try enabling debug logs:

```
NVIM_PYTHON_LOG_FILE=/tmp/neovim ENSIME_VIM_DEBUG=1 nvim <yourfile>
```

That should produce a few log files from the Neovim Python client in `/tmp` prefixed with `neovim_`. The file `/tmp/neovim_py2_rplugin` should be all that we need, if you can post the contents of that to a pastebin that should give us a hint what to try next.

**Comment by yelled1** [comment]
Hi: Put the files as below.
[nvimLogsEnTypeErrors.zip](https://github.com/ensime/ensime-vim/files/1347437/nvimLogsEnTypeErrors.zip)
And just to make sure, I put them in:
[https://github.com/yelled1/uMarkCLewiss/blob/master/nvimLogsEnTypeErrors.zip](url)
Thank u!

**Comment by mlopes** [comment]
I have the same problem, latest ensime-vim, and neovim 0.2.0.

**Comment by mlopes** [comment]
This seems to be the relevant bit of the logs:

```
2017-10-06 11:47:47,780 [DEBUG @ client.py:doc_browse:449] 21031 - browse: in
2017-10-06 11:47:47,780 [DEBUG @ client.py:send_at_position:259] 21031 - send_at_position: in
2017-10-06 11:47:47,785 [DEBUG @ client.py:send_at_position:261] 21031 - useSelection: False, beg: [22, 4], end: [22, 7]
2017-10-06 11:47:47,785 [DEBUG @ client.py:get_position:284] 21031 - 22 4
2017-10-06 11:47:47,787 [DEBUG @ client.py:get_position:287] 21031 - 583
2017-10-06 11:47:47,788 [DEBUG @ client.py:get_position:284] 21031 - 22 7
2017-10-06 11:47:47,790 [DEBUG @ client.py:get_position:287] 21031 - 586
2017-10-06 11:47:47,796 [DEBUG @ client.py:send_request:571] 21031 - send_request: in
2017-10-06 11:47:47,799 [DEBUG @ client.py:send_request:574] 21031 - send_request:
{'callId': 1,
 'req': {'file': '/home/mlopes/Projects/thornbury/app/controllers/HomeController.scala',
         'point': {'from': 583, 'to': 586},
         'typehint': 'DocUriAtPointReq'}}
2017-10-06 11:47:47,802 [DEBUG @ client.py:send:199] 21031 - send: in
2017-10-06 11:47:47,804 [DEBUG @ client.py:send:202] 21031 - send: sending JSON on WebSocket
2017-10-06 11:47:47,954 [DEBUG @ client.py:unqueue:607] 21031 - unqueue: result received
{
  "callId": 1,
  "payload": {
    "typehint": "StringResponse",
    "text": "docs/scala-library-2.12.3-javadoc.jar/scala/collection/immutable/List$.html"
  }
}
2017-10-06 11:47:47,954 [DEBUG @ protocol.py:handle_incoming_response:52] 21031 - handle_incoming_response: in [typehint: StringResponse, call ID: 1]
2017-10-06 11:47:47,954 [DEBUG @ protocol.py:handle_string_response:211] 21031 - handle_string_response: in [typehint: StringResponse, call ID: 1]
2017-10-06 11:47:47,955 [DEBUG @ protocol.py:_browse_doc:229] 21031 - _browse_doc: http://127.0.0.1:38919/docs/scala-library-2.12.3-javadoc.jar/scala/collection/immutable/List$.html
2017-10-06 11:47:47,959 [INFO @ protocol.py:_browse_doc:232] 21031 - opened http://127.0.0.1:38919/docs/scala-library-2.12.3-javadoc.jar/scala/collection/immutable/List$.html
2017-10-06 11:47:48,386 [WARNING @ async_session.py:_on_message:78] 21031 - Traceback (most recent call last):
  File "/home/mlopes/.local/lib/python2.7/site-packages/neovim/msgpack_rpc/async_session.py", line 75, in _on_message
    self._handlers.get(msg[0], self._on_invalid_message)(msg)
  File "/home/mlopes/.local/lib/python2.7/site-packages/neovim/msgpack_rpc/async_session.py", line 96, in _on_response
    self._pending_requests.pop(msg[1])(msg[2], msg[3])
KeyError: 18446744073709551615L
```

Let me know if I should paste the whole thing here. It's worth to note that it actually opens the URL in the web browser, but vim will continue reporting : 

```
Error detected while processing function EnTick:
line    1:

E475: Invalid argument: Channel doesn't exist
```

The second bit will just run indefinitely rendering neovim unusable until a restart is made.

**Comment by yelled1** [comment]
Here's something extra.
I changed Browser by export BROWSER="gnome-open %s"
As long as I leave the browser open it does NOT come back with the Annoying/Repeating error msg.
As soon as I close, it returns. If this works then it's good for me for now.
I attempted:
- sensible-browser
- xdg-open
- firefox
- x-www-browser
Likely due to python issue.

Below did NOT work: https://github.com/ensime/ensime-vim/pull/226#issuecomment-207468659
Prob because I am on Ubuntu 16.04

**Comment by yelled1** [comment]
Also when I just point to a file like $ export BROWSER="/Users/ches/bin/vim-browser %s"
$ chmod a+x ~/bin/vim-browser
Contents of vim-browser:
#!/bin/sh
echo "$@" >> /tmp/EnDoc.txt
without launching a browser, then it does NOT give out those annyong errors. I am actually thinking about writing a script to pickup the tail of that file or something like that kind of poorman's hack. Not pretty but will get the job done.

**Comment by yelled1** [comment]
Here's a simple work around.  
let $BROWSER = '/usr/bin/firefox %s' in your init.vim file. 
No hacks needed! :smiley_cat:

**Comment by mlopes** [comment]
@yelled1 not sure if you should have closed it. I've tried that, it doesn't cause the error when it opens the documentation, but when you close the browser it starts showing the error again.
It immediatelly happened in my case because I don't actually use Firefox, so I closed it as soon as I finshed testing.
So, yes, this delays the error, it stops happening when opening the documentation, but it will happen again as soon as the browser is closed.

**Comment by yelled1** [comment]
Ok, will Reopen. Yep you need to leave the browser open. And this causes the nvim not to close until browser closes, then as you said the error msg appear then nvim closes.
So, it is a bug as you pointed out.  :frowning_woman: 
Still, I can now see some darn docs & keep on editing. An improved bug? :unamused:

**Comment by yelled1** [comment]
Just adding. I tried & works with a caveat: 
```
let $BROWSER = '/usr/bin/epiphany %s'
```
So, this might b chrome issue? 
A strange side effect, however, is that chrome keeps on adding web page tabs when called but epiphany will not allow adding tabs. One must close the open browser & it will bring up another one.
So, neither is perfect but hopefully this helps to id the issue.
Thanks much,
