### ISSUE TITLE
Error in EnCompleteFunc

### ISSUE THREAD

**Issue by oscar-broman** [ensime/ensime-vim#88]
I'm using Neovim (latest version as of now).

When I do C-x C-o I get this:
```
Error detected while processing function EnCompleteFunc:
line    1:
TypeError('fun_en_complete_func() takes exactly 3 arguments (2 given)',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python2.7/site-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/local/lib/python2.7/site-packages/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
TypeError: fun_en_complete_func() takes exactly 3 arguments (2 given)
```

How do I further debug this? I'm not too familiar with vim scripting or python.

It works just fine in Vim.

**Comment by yazgoo** [comment]
Please re-open if it does not fix it on your end.

**Comment by oscar-broman** [comment]
Works! Thanks.
